class Food {
  final String id;
  final String name;
  final String source;
  final String image;
  final String age;
  final double energy;
  final double fat;
  final double protein;
  final String portion;
  final List<String> fruit;
  final List<String> recipe;
  final List<String> step;
  final String description;
  final String foodCategoryId;
  bool isFavorite;

  Food({
    required this.id,
    required this.name,
    required this.source,
    required this.image,
    required this.age,
    required this.energy,
    required this.protein,
    required this.fat,
    required this.portion,
    required this.fruit,
    required this.recipe,
    required this.step,
    required this.description,
    required this.foodCategoryId,
    required this.isFavorite,
  });

  // Data dummy makanan
  static List<Food> dummyFoods = [
    Food(
      id: '1',
      name: 'Bubur Sup Daging Kacang',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=1',
      age: '6-8 bulan',
      energy: 150.0,
      protein: 6.5,
      fat: 10.0,
      portion: '2',
      fruit: ['Wortel', 'Bayam', 'Kacang Merah'],
      recipe: [
        '100g daging sapi',
        '50g wortel',
        '30g bayam',
        '50g kacang merah',
      ],
      step: [
        'Cuci semua bahan hingga bersih',
        'Potong daging menjadi ukuran kecil',
        'Rebus daging hingga empuk',
        'Tambahkan sayuran dan kacang',
        'Masak hingga matang dan tekstur sesuai',
      ],
      description:
          'Bubur lembut dengan kombinasi daging dan kacang yang kaya protein serta sayuran untuk nutrisi optimal bayi. Bubur lembut dengan kombinasi daging dan kacang yang kaya protein serta sayuran untuk nutrisi optimal bayi.',
      foodCategoryId: '1',
      isFavorite: true,
    ),
    Food(
      id: '2',
      name: 'Pure Alpukat Pisang',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=2',
      age: '6-8 bulan',
      energy: 120.0,
      protein: 2.0,
      fat: 10.0,
      portion: '3',
      fruit: ['Alpukat', 'Pisang'],
      recipe: ['1 buah alpukat matang', '1 buah pisang matang'],
      step: [
        'Kupas alpukat dan pisang',
        'Haluskan alpukat',
        'Haluskan pisang',
        'Campur kedua buah',
        'Aduk hingga rata',
      ],
      description:
          'Pure buah yang lembut dan kaya akan nutrisi dari kombinasi alpukat dan pisang.',
      foodCategoryId: '1',
      isFavorite: false,
    ),
    Food(
      id: '3',
      name: 'Nasi Tim Ayam Wortel',
      source: 'WHO',
      image: 'https://picsum.photos/200/300?random=3',
      age: '9-11 bulan',
      energy: 180.0,
      protein: 8.0,
      fat: 10.0,
      portion: '2',
      fruit: ['Wortel', 'Brokoli'],
      recipe: ['100g beras', '50g ayam', '30g wortel', '30g brokoli'],
      step: [
        'Cuci beras hingga bersih',
        'Potong ayam kecil-kecil',
        'Potong sayuran sesuai ukuran',
        'Tim beras bersama ayam',
        'Tambahkan sayuran di akhir',
      ],
      description:
          'Nasi tim dengan potongan ayam dan sayuran yang cocok untuk bayi yang mulai mengenal tekstur makanan.',
      foodCategoryId: '4',
      isFavorite: true,
    ),
    Food(
      id: '4',
      name: 'Finger Food Kentang Keju',
      source: 'KEMENKES',
      image: 'https://picsum.photos/200/300?random=4',
      age: '12-23 bulan',
      energy: 200.0,
      protein: 5.0,
      fat: 10.0,
      portion: '3',
      fruit: ['Kentang', 'Keju'],
      recipe: ['200g kentang', '50g keju cheddar', 'Bumbu secukupnya'],
      step: [
        'Kukus kentang hingga empuk',
        'Haluskan kentang',
        'Campurkan dengan keju parut',
        'Bentuk bulat pipih',
        'Panggang hingga kecokelatan',
      ],
      description:
          'Camilan sehat berbentuk finger food yang cocok untuk melatih kemampuan makan mandiri.',
      foodCategoryId: '3',
      isFavorite: false,
    ),
    Food(
      id: '5',
      name: 'Sup Ikan Salmon',
      source: 'WHO',
      image: 'https://picsum.photos/200/300?random=5',
      age: '9-11 bulan',
      energy: 160.0,
      protein: 10.0,
      fat: 10.0,
      portion: '2',
      fruit: ['Wortel', 'Kentang', 'Brokoli'],
      recipe: ['100g ikan salmon', '30g wortel', '30g kentang', '30g brokoli'],
      step: [
        'Bersihkan ikan dan potong dadu',
        'Potong sayuran sesuai ukuran',
        'Rebus kentang dan wortel',
        'Masukkan ikan salmon',
        'Tambahkan brokoli di akhir',
      ],
      description:
          'Sup ikan salmon yang kaya omega-3 dengan tambahan sayuran untuk tumbuh kembang optimal.',
      foodCategoryId: '2',
      isFavorite: false,
    ),
    Food(
      id: '6',
      name: 'Biskuit Oatmeal Apel',
      source: 'KEMENKES',
      image: 'https://picsum.photos/200/300?random=6',
      age: '12-23 bulan',
      energy: 140.0,
      protein: 3.0,
      fat: 5.0,
      portion: '4',
      fruit: ['Apel', 'Oatmeal'],
      recipe: [
        '100g oatmeal',
        '1 buah apel',
        '1 butir telur',
        '30ml minyak zaitun',
        'Kayu manis secukupnya',
      ],
      step: [
        'Parut apel hingga halus',
        'Campurkan oatmeal dengan apel parut',
        'Tambahkan telur dan minyak zaitun',
        'Bentuk adonan menjadi biskuit kecil',
        'Panggang dalam oven hingga kecokelatan',
      ],
      description:
          'Biskuit oatmeal dengan apel yang kaya serat dan rendah gula, cocok sebagai camilan sehat untuk balita.',
      foodCategoryId: '5',
      isFavorite: false,
    ),
    Food(
      id: '7',
      name: 'Bubur Kacang Hijau',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=7',
      age: '6-8 bulan',
      energy: 130.0,
      protein: 4.0,
      fat: 2.0,
      portion: '2',
      fruit: ['Kacang Hijau', 'Labu Kuning'],
      recipe: [
        '100g kacang hijau',
        '50g labu kuning',
        '200ml air',
        'Daun pandan secukupnya',
      ],
      step: [
        'Rendam kacang hijau selama 2 jam',
        'Rebus kacang hijau hingga empuk',
        'Tambahkan labu kuning yang sudah dipotong dadu',
        'Masak hingga labu lembut',
        'Haluskan sesuai tekstur yang diinginkan',
      ],
      description:
          'Bubur kacang hijau dengan tambahan labu kuning yang kaya akan vitamin A dan serat untuk pencernaan bayi yang sehat.',
      foodCategoryId: '1',
      isFavorite: true,
    ),
    Food(
      id: '8',
      name: 'Nugget Ayam Sayur',
      source: 'WHO',
      image: 'https://picsum.photos/200/300?random=8',
      age: '12-23 bulan',
      energy: 180.0,
      protein: 12.0,
      fat: 8.0,
      portion: '3',
      fruit: ['Wortel', 'Bayam', 'Brokoli'],
      recipe: [
        '150g daging ayam giling',
        '30g wortel',
        '30g bayam',
        '30g brokoli',
        '1 butir telur',
        'Tepung panir secukupnya',
      ],
      step: [
        'Haluskan semua sayuran',
        'Campurkan dengan daging ayam giling',
        'Tambahkan telur sebagai pengikat',
        'Bentuk sesuai keinginan',
        'Balut dengan tepung panir',
        'Kukus hingga matang',
      ],
      description:
          'Nugget ayam dengan campuran sayuran yang tersembunyi, cocok untuk balita yang sulit makan sayur.',
      foodCategoryId: '3',
      isFavorite: true,
    ),
    Food(
      id: '9',
      name: 'Bubur Sumsum Kurma',
      source: 'KEMENKES',
      image: 'https://picsum.photos/200/300?random=9',
      age: '9-11 bulan',
      energy: 150.0,
      protein: 2.0,
      fat: 3.0,
      portion: '2',
      fruit: ['Kurma'],
      recipe: [
        '100g tepung beras',
        '500ml santan encer',
        '3 buah kurma',
        'Daun pandan secukupnya',
      ],
      step: [
        'Haluskan kurma',
        'Rebus santan dengan daun pandan',
        'Larutkan tepung beras dengan sedikit air',
        'Tuang larutan tepung ke dalam santan',
        'Aduk hingga mengental',
        'Tambahkan kurma halus sebagai pemanis',
      ],
      description:
          'Bubur sumsum dengan kurma sebagai pemanis alami, kaya kalsium dan zat besi untuk pertumbuhan tulang dan darah.',
      foodCategoryId: '1',
      isFavorite: false,
    ),
    Food(
      id: '10',
      name: 'Sup Jagung Manis',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=10',
      age: '9-11 bulan',
      energy: 120.0,
      protein: 4.0,
      fat: 3.0,
      portion: '2',
      fruit: ['Jagung Manis', 'Wortel', 'Tofu'],
      recipe: [
        '1 buah jagung manis',
        '50g wortel',
        '50g tofu',
        '300ml kaldu ayam',
        'Seledri secukupnya',
      ],
      step: [
        'Pipil jagung manis',
        'Potong wortel dan tofu dadu kecil',
        'Rebus kaldu hingga mendidih',
        'Masukkan jagung dan wortel',
        'Tambahkan tofu di akhir',
        'Taburi dengan seledri cincang',
      ],
      description:
          'Sup jagung manis dengan tambahan tofu yang lembut, kaya akan protein nabati dan vitamin untuk tumbuh kembang optimal.',
      foodCategoryId: '2',
      isFavorite: true,
    ),
    Food(
      id: '11',
      name: 'Puding Ubi Ungu',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=11',
      age: '9-11 bulan',
      energy: 110.0,
      protein: 2.0,
      fat: 1.5,
      portion: '3',
      fruit: ['Ubi Ungu'],
      recipe: [
        '200g ubi ungu',
        '200ml susu UHT',
        '1 sdm agar-agar plain',
        '2 sdm madu (opsional)',
      ],
      step: [
        'Kupas dan potong ubi ungu',
        'Kukus ubi hingga empuk',
        'Haluskan ubi dengan blender',
        'Campurkan susu dan agar-agar',
        'Masak hingga mendidih',
        'Tuang ke dalam cetakan',
        'Dinginkan dalam kulkas',
      ],
      description:
          'Puding ubi ungu yang lembut dan kaya akan antioksidan, cocok sebagai makanan penutup sehat untuk bayi yang mulai mengenal rasa manis alami.',
      foodCategoryId: '5',
      isFavorite: false,
    ),
    Food(
      id: '12',
      name: 'Nasi Tim Hati Ayam',
      source: 'WHO',
      image: 'https://picsum.photos/200/300?random=12',
      age: '9-11 bulan',
      energy: 170.0,
      protein: 9.0,
      fat: 5.0,
      portion: '2',
      fruit: ['Wortel', 'Buncis', 'Bayam'],
      recipe: [
        '100g beras',
        '50g hati ayam',
        '30g wortel',
        '30g buncis',
        '20g bayam',
        'Bawang putih secukupnya',
      ],
      step: [
        'Cuci beras hingga bersih',
        'Rebus hati ayam hingga matang',
        'Potong hati ayam kecil-kecil',
        'Potong sayuran sesuai ukuran',
        'Tim beras bersama hati ayam',
        'Tambahkan sayuran di akhir',
      ],
      description:
          'Nasi tim dengan hati ayam yang kaya zat besi dan vitamin A, sangat baik untuk mencegah anemia dan mendukung perkembangan penglihatan bayi.',
      foodCategoryId: '4',
      isFavorite: true,
    ),
    Food(
      id: '13',
      name: 'Pancake Pisang Mini',
      source: 'KEMENKES',
      image: 'https://picsum.photos/200/300?random=13',
      age: '12-23 bulan',
      energy: 150.0,
      protein: 4.0,
      fat: 3.0,
      portion: '4',
      fruit: ['Pisang'],
      recipe: [
        '1 buah pisang matang',
        '100g tepung terigu',
        '1 butir telur',
        '100ml susu UHT',
        '1/2 sdt baking powder',
      ],
      step: [
        'Haluskan pisang dengan garpu',
        'Campurkan semua bahan kering',
        'Tambahkan telur dan susu',
        'Aduk hingga rata',
        'Panaskan teflon anti lengket',
        'Tuang adonan kecil-kecil',
        'Masak hingga kedua sisi kecokelatan',
      ],
      description:
          'Pancake mini dengan pisang yang lembut dan mudah digenggam, cocok sebagai finger food untuk balita yang sedang belajar makan sendiri.',
      foodCategoryId: '3',
      isFavorite: false,
    ),
    Food(
      id: '14',
      name: 'Bubur Labu Kuning Daging',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=14',
      age: '6-8 bulan',
      energy: 140.0,
      protein: 7.0,
      fat: 4.0,
      portion: '2',
      fruit: ['Labu Kuning', 'Wortel'],
      recipe: [
        '100g labu kuning',
        '50g daging sapi giling',
        '30g wortel',
        '2 sdm beras',
        'Daun salam secukupnya',
      ],
      step: [
        'Cuci beras hingga bersih',
        'Potong labu dan wortel dadu kecil',
        'Rebus daging hingga empuk',
        'Masak beras hingga menjadi bubur',
        'Tambahkan labu dan wortel',
        'Masukkan daging yang sudah empuk',
        'Aduk hingga semua bahan tercampur rata',
      ],
      description:
          'Bubur labu kuning dengan daging yang kaya akan zat besi dan vitamin A, sangat baik untuk perkembangan otak dan penglihatan bayi.',
      foodCategoryId: '1',
      isFavorite: true,
    ),
    Food(
      id: '15',
      name: 'Sup Bola-Bola Ikan',
      source: 'WHO',
      image: 'https://picsum.photos/200/300?random=15',
      age: '9-11 bulan',
      energy: 160.0,
      protein: 12.0,
      fat: 6.0,
      portion: '2',
      fruit: ['Wortel', 'Brokoli', 'Kentang'],
      recipe: [
        '100g ikan dori',
        '1 butir telur',
        '30g wortel',
        '30g brokoli',
        '50g kentang',
        '300ml kaldu ikan',
      ],
      step: [
        'Haluskan ikan dori',
        'Campurkan dengan telur',
        'Bentuk menjadi bola-bola kecil',
        'Rebus kaldu hingga mendidih',
        'Masukkan bola-bola ikan',
        'Tambahkan sayuran yang sudah dipotong',
        'Masak hingga matang',
      ],
      description:
          'Sup dengan bola-bola ikan yang lembut dan sayuran berwarna-warni, kaya akan protein dan nutrisi penting untuk tumbuh kembang bayi.',
      foodCategoryId: '2',
      isFavorite: false,
    ),
    Food(
      id: '16',
      name: 'Stik Tempe Bayam',
      source: 'KEMENKES',
      image: 'https://picsum.photos/200/300?random=16',
      age: '12-23 bulan',
      energy: 130.0,
      protein: 8.0,
      fat: 5.0,
      portion: '3',
      fruit: ['Bayam'],
      recipe: [
        '100g tempe',
        '50g bayam',
        '1 butir telur',
        '50g tepung terigu',
        'Bumbu secukupnya',
      ],
      step: [
        'Kukus tempe hingga empuk',
        'Rebus bayam sebentar',
        'Haluskan tempe dan bayam',
        'Campurkan dengan telur dan tepung',
        'Bentuk memanjang seperti stik',
        'Kukus hingga matang',
      ],
      description:
          'Stik tempe bayam yang kaya protein nabati dan zat besi, cocok sebagai finger food sehat untuk balita yang aktif bergerak.',
      foodCategoryId: '3',
      isFavorite: true,
    ),
    Food(
      id: '17',
      name: 'Pure Buah Naga Pepaya',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=17',
      age: '6-8 bulan',
      energy: 100.0,
      protein: 1.5,
      fat: 0.5,
      portion: '2',
      fruit: ['Buah Naga', 'Pepaya'],
      recipe: [
        '1/2 buah naga merah',
        '100g pepaya matang',
        '1 sdm yogurt plain (opsional)',
      ],
      step: [
        'Kupas buah naga dan pepaya',
        'Potong dadu kecil',
        'Haluskan dengan blender',
        'Tambahkan yogurt jika diinginkan',
        'Aduk hingga rata',
      ],
      description:
          'Pure buah dengan kombinasi buah naga dan pepaya yang kaya akan serat, vitamin C, dan enzim pencernaan, sangat baik untuk sistem pencernaan bayi.',
      foodCategoryId: '1',
      isFavorite: false,
    ),
    Food(
      id: '18',
      name: 'Nasi Goreng Sayur Mini',
      source: 'WHO',
      image: 'https://picsum.photos/200/300?random=18',
      age: '12-23 bulan',
      energy: 180.0,
      protein: 6.0,
      fat: 5.0,
      portion: '2',
      fruit: ['Wortel', 'Kacang Polong', 'Jagung Manis'],
      recipe: [
        '100g nasi putih',
        '30g wortel',
        '30g kacang polong',
        '30g jagung manis',
        '1 butir telur',
        'Bumbu secukupnya',
      ],
      step: [
        'Potong wortel dadu kecil',
        'Rebus kacang polong dan jagung',
        'Kocok telur',
        'Tumis telur hingga matang',
        'Masukkan nasi dan sayuran',
        'Aduk rata dengan api kecil',
      ],
      description:
          'Nasi goreng mini dengan beragam sayuran berwarna-warni, menyediakan karbohidrat kompleks dan vitamin untuk energi balita sepanjang hari.',
      foodCategoryId: '4',
      isFavorite: true,
    ),
    Food(
      id: '19',
      name: 'Smoothie Bowl Buah Naga',
      source: 'Pengguna',
      image: 'https://picsum.photos/200/300?random=19',
      age: '12-23 bulan',
      energy: 130.0,
      protein: 3.0,
      fat: 2.0,
      portion: '2',
      fruit: ['Buah Naga', 'Pisang', 'Stroberi'],
      recipe: [
        '1 buah naga merah',
        '1 buah pisang beku',
        '50g stroberi',
        '100ml yogurt plain',
        '1 sdm granola (untuk topping)',
        '1 sdt chia seed (untuk topping)',
      ],
      step: [
        'Potong buah naga dan pisang',
        'Bekukan buah selama minimal 2 jam',
        'Blender buah beku dengan yogurt',
        'Tuang ke dalam mangkuk',
        'Taburi dengan granola dan chia seed',
        'Sajikan segera',
      ],
      description:
          'Smoothie bowl dengan kombinasi buah naga, pisang, dan stroberi yang kaya antioksidan dan vitamin C. Teksturnya yang kental dan dingin sangat disukai balita, terutama saat cuaca panas.',
      foodCategoryId: '5',
      isFavorite: false,
    ),
    Food(
      id: '20',
      name: 'Risoles Ayam Sayur',
      source: 'KEMENKES',
      image: 'https://picsum.photos/200/300?random=20',
      age: '12-23 bulan',
      energy: 190.0,
      protein: 8.0,
      fat: 7.0,
      portion: '3',
      fruit: ['Wortel', 'Buncis', 'Jagung Manis'],
      recipe: [
        '100g tepung terigu',
        '1 butir telur',
        '200ml susu cair',
        '50g ayam cincang',
        '30g wortel',
        '30g buncis',
        '30g jagung manis',
        'Bumbu secukupnya',
      ],
      step: [
        'Buat adonan kulit dengan tepung, telur, dan susu',
        'Tumis ayam cincang hingga matang',
        'Tambahkan sayuran yang sudah dipotong kecil',
        'Buat kulit dadar tipis-tipis',
        'Isi dengan tumisan ayam dan sayur',
        'Gulung dan rekatkan ujungnya',
        'Kukus hingga matang',
      ],
      description:
          'Risoles dengan isian ayam dan sayuran yang bergizi, dimasak dengan cara dikukus sehingga lebih sehat untuk balita. Teksturnya yang lembut membuatnya mudah dikonsumsi dan kaya akan protein serta serat.',
      foodCategoryId: '3',
      isFavorite: true,
    ),
  ];
}
